@baseUrl=http://localhost:3000/api/v1
@token={{login.response.body.data.token}}
@orderId={{orders.response.body.data[0].id}}
@bookId={{books.response.body.data[0].id}}

### Get orders
# @name orders
GET {{baseUrl}}/orders
Content-Type: application/json
X-Session-Token: {{token}}

### Get order
GET {{baseUrl}}/orders/{{orderId}}
Content-Type: application/json
X-Session-Token: {{token}}

### Create order
POST {{baseUrl}}/orders
Content-Type: application/json
X-Session-Token: {{token}}

{
    "items": [
        {
            "book_id": "{{bookId}}",
            "quantity": 4
        }
    ]
}

### Login account
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "sky@gmail.com",
    "password": "123456"
}

### Get books
# @name books
GET {{baseUrl}}/books
